#!/usr/bin/env bash
# Deploy a simple in-cluster NFS server exporting /nfsshare.
# Backed by minikube's default hostPath storage (no Ceph).
#
# Usage:     ./deploy-nfs.sh
# Uninstall: ./deploy-nfs.sh --uninstall

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

NAMESPACE="nfs"
BACKING_SC="standard"
SIZE="10Gi"
SERVER_NAME="nfs-server"

if [[ "${1:-}" == "--uninstall" ]]; then
  kubectl delete ns "${NAMESPACE}" --ignore-not-found
  exit 0
fi

kubectl get ns "${NAMESPACE}" >/dev/null 2>&1 || kubectl create ns "${NAMESPACE}"

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${SERVER_NAME}-backing
  namespace: ${NAMESPACE}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ${BACKING_SC}
  resources:
    requests:
      storage: ${SIZE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVER_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels: { app: ${SERVER_NAME} }
  template:
    metadata:
      labels: { app: ${SERVER_NAME} }
    spec:
      containers:
        - name: nfs
          image: itsthenetwork/nfs-server-alpine:latest
          securityContext:
            privileged: true
          env:
            - name: SHARED_DIRECTORY
              value: /nfsshare
          ports:
            - { name: nfs, containerPort: 2049 }
          volumeMounts:
            - name: data
              mountPath: /nfsshare
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ${SERVER_NAME}-backing
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVER_NAME}
  namespace: ${NAMESPACE}
spec:
  selector: { app: ${SERVER_NAME} }
  ports:
    - { name: nfs, port: 2049, targetPort: 2049 }
EOF

echo "Waiting for NFS server to be ready..."
kubectl rollout status -n "${NAMESPACE}" deploy/${SERVER_NAME} --timeout=180s

CLUSTER_IP=$(kubectl get svc -n "${NAMESPACE}" "${SERVER_NAME}" -o jsonpath='{.spec.clusterIP}')

CHART_DIR="$(cd "${SCRIPT_DIR}/../../infra/charts/kyper-ds-platform" && pwd)"
VALUES_FILE="${CHART_DIR}/values-nfs.yaml"
cat > "${VALUES_FILE}" <<EOF
# Auto-generated by deploy-nfs.sh — NFS server ClusterIP for oxy-data PV.
oxy:
  nfs:
    server: ${CLUSTER_IP}
    path: /
EOF

echo
echo "NFS server ClusterIP: ${CLUSTER_IP}  (export path: /)"
echo "Wrote ${VALUES_FILE}"
echo "Include it in helm: -f values.yaml -f values-minikube.yaml -f values-nfs.yaml"
