{{- if .Values.mlflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: {{ .Values.global.namespace.platform }}
  labels:
    {{- include "kyper.labels" . | nindent 4 }}
    app.kubernetes.io/component: mlflow
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
  selector:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
